name: Publish

on:
  push:
    branches:
      

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  edge:
    name: Update edge docs
    runs-on: ubuntu-latest

    steps:
      - name: show version
        continue-on-error: true
        shell: bash
        run: |
          docker --help
      - name: compose version
        continue-on-error: true
        shell: bash
        run: |
          docker compose --help
